# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_quest', '0002_auto_20170415_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queststages',
            name='proof',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
