# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_quest', '0005_auto_20170415_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queststages',
            name='quest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='real_quest.QuestModel'),
        ),
    ]
