# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_quest', '0008_auto_20170415_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queststages',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='real_quest.QuestModel'),
        ),
    ]
